language: c
dist: trusty

compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      binutils-dev
      libreadline-dev
      libnl-3-dev
      libnl-genl-3-dev

script: ./autogen.sh && ./configure && make && make check 

after_script: cat ./tests/rundropwatch.sh.log

